export type CategorySeed = {
  systemKey: string;
  name: string;
  kind: "expense" | "income";
  examples: readonly string[];
  sortOrder: number;
};

export const categorySeeds: readonly CategorySeed[] = [
  {
    systemKey: "expense.food-drink",
    name: "Food & Drink",
    kind: "expense",
    examples: [
      "coffee",
      "cafe",
      "restaurant",
      "lunch",
      "dinner",
      "takeaway",
      "fast food",
      "bakery",
    ],
    sortOrder: 10,
  },
  {
    systemKey: "expense.groceries",
    name: "Groceries",
    kind: "expense",
    examples: [
      "supermarket",
      "grocery store",
      "vegetables",
      "food market",
      "food shopping",
      "butcher",
      "produce",
      "pantry",
    ],
    sortOrder: 20,
  },
  {
    systemKey: "expense.fuel",
    name: "Fuel",
    kind: "expense",
    examples: [
      "gas",
      "gasoline",
      "petrol",
      "diesel",
      "fuel station",
      "service station",
      "charging station",
      "car fuel",
    ],
    sortOrder: 30,
  },
  {
    systemKey: "expense.transport",
    name: "Transport",
    kind: "expense",
    examples: [
      "taxi",
      "bus",
      "train",
      "subway",
      "ride share",
      "parking",
      "toll road",
      "public transit",
    ],
    sortOrder: 40,
  },
  {
    systemKey: "expense.housing",
    name: "Housing",
    kind: "expense",
    examples: [
      "rent",
      "mortgage",
      "property maintenance",
      "home repair",
      "apartment",
      "homeowners association",
      "landlord",
      "property fee",
    ],
    sortOrder: 50,
  },
  {
    systemKey: "expense.utilities",
    name: "Utilities",
    kind: "expense",
    examples: [
      "electricity",
      "water bill",
      "heating",
      "natural gas bill",
      "internet bill",
      "phone bill",
      "waste collection",
      "utility bill",
    ],
    sortOrder: 60,
  },
  {
    systemKey: "expense.shopping",
    name: "Shopping",
    kind: "expense",
    examples: [
      "clothes",
      "electronics",
      "online order",
      "department store",
      "shoes",
      "household goods",
      "retail",
      "purchase",
    ],
    sortOrder: 70,
  },
  {
    systemKey: "expense.health",
    name: "Health",
    kind: "expense",
    examples: [
      "pharmacy",
      "doctor",
      "dentist",
      "hospital",
      "clinic",
      "medicine",
      "therapy",
      "optician",
    ],
    sortOrder: 80,
  },
  {
    systemKey: "expense.insurance",
    name: "Insurance",
    kind: "expense",
    examples: [
      "car insurance",
      "health insurance",
      "home insurance",
      "life insurance",
      "insurance premium",
      "policy payment",
      "insurer",
      "coverage",
    ],
    sortOrder: 90,
  },
  {
    systemKey: "expense.entertainment",
    name: "Entertainment",
    kind: "expense",
    examples: [
      "cinema",
      "movie",
      "concert",
      "video game",
      "museum",
      "streaming rental",
      "nightclub",
      "event ticket",
    ],
    sortOrder: 100,
  },
  {
    systemKey: "expense.education",
    name: "Education",
    kind: "expense",
    examples: [
      "school",
      "tuition",
      "course",
      "textbooks",
      "training",
      "university",
      "class",
      "exam fee",
    ],
    sortOrder: 110,
  },
  {
    systemKey: "expense.travel",
    name: "Travel",
    kind: "expense",
    examples: [
      "hotel",
      "flight",
      "vacation",
      "luggage",
      "travel booking",
      "hostel",
      "resort",
      "sightseeing",
    ],
    sortOrder: 120,
  },
  {
    systemKey: "expense.subscriptions",
    name: "Subscriptions",
    kind: "expense",
    examples: [
      "video subscription",
      "music subscription",
      "membership",
      "software subscription",
      "monthly plan",
      "cloud storage",
      "newspaper subscription",
      "app subscription",
    ],
    sortOrder: 130,
  },
  {
    systemKey: "expense.fees-charges",
    name: "Fees & Charges",
    kind: "expense",
    examples: [
      "bank fee",
      "service charge",
      "commission",
      "late fee",
      "atm fee",
      "interest charge",
      "penalty",
      "transaction fee",
    ],
    sortOrder: 140,
  },
  {
    systemKey: "expense.gifts-donations",
    name: "Gifts & Donations",
    kind: "expense",
    examples: [
      "charity",
      "donation",
      "present",
      "birthday gift",
      "fundraiser",
      "nonprofit",
      "church donation",
      "gift for friend",
    ],
    sortOrder: 150,
  },
  {
    systemKey: "expense.other",
    name: "Other",
    kind: "expense",
    examples: [
      "miscellaneous",
      "uncategorized",
      "unknown expense",
      "cash expense",
    ],
    sortOrder: 160,
  },
  {
    systemKey: "income.salary",
    name: "Salary",
    kind: "income",
    examples: [
      "salary",
      "paycheck",
      "wages",
      "payroll",
      "bonus",
      "employer payment",
      "monthly pay",
      "compensation",
    ],
    sortOrder: 10,
  },
  {
    systemKey: "income.business-freelance",
    name: "Business & Freelance",
    kind: "income",
    examples: [
      "freelance",
      "client payment",
      "invoice paid",
      "consulting",
      "side job",
      "business income",
      "contract work",
      "sales revenue",
    ],
    sortOrder: 20,
  },
  {
    systemKey: "income.investments",
    name: "Investments",
    kind: "income",
    examples: [
      "dividend",
      "interest income",
      "capital gain",
      "investment return",
      "bond interest",
      "stock income",
      "portfolio payout",
      "savings interest",
    ],
    sortOrder: 30,
  },
  {
    systemKey: "income.refunds",
    name: "Refunds",
    kind: "income",
    examples: [
      "refund",
      "reimbursement",
      "cashback",
      "returned purchase",
      "chargeback",
      "rebate",
      "tax refund",
      "repayment",
    ],
    sortOrder: 40,
  },
  {
    systemKey: "income.gifts-received",
    name: "Gifts Received",
    kind: "income",
    examples: [
      "gift received",
      "birthday money",
      "family gift",
      "cash gift",
      "present money",
      "donation received",
      "inheritance",
      "prize",
    ],
    sortOrder: 50,
  },
  {
    systemKey: "income.other",
    name: "Other",
    kind: "income",
    examples: [
      "other income",
      "cash income",
      "deposit",
      "credit received",
      "money received",
      "incoming payment",
      "windfall",
      "unknown income",
    ],
    sortOrder: 60,
  },
];
