import SwiftUI

enum AppIconCatalog {
    // Curate selectable entity icons separately from AppIcons' saved-artwork compatibility map.
    static let groups: [IconPickerGroup] = [
        group("General", symbol: "label", icons: [
            ("label", "Tag"),
            ("star", "Star"),
            ("heart", "Heart"),
            ("folder", "Folder"),
            ("gift", "Gift"),
            ("calendar", "Calendar"),
        ]),
        group("Money & accounts", symbol: "wallet", icons: [
            ("cash", "Cash"),
            ("credit-card", "Credit card"),
            ("bank", "Bank"),
            ("wallet", "Wallet"),
            ("coins", "Coins"),
            ("piggy-bank", "Savings"),
            ("target", "Savings goal"),
            ("safe", "Reserves"),
            ("graph-up", "Investments"),
            ("percentage", "Interest & fees"),
            ("taxes", "Taxes"),
            ("page", "Bills & receipts"),
            ("percentage-circle", "Budget"),
            ("repeat", "Recurring payment"),
            ("coins-swap", "Transfer"),
            ("undo", "Refund"),
            ("charity", "Donations"),
        ]),
        group("Food & drink", symbol: "cutlery", icons: [
            ("cutlery", "Meal"),
            ("coffee-cup", "Coffee"),
            ("pizza-slice", "Takeout"),
            ("cart", "Groceries"),
            ("birthday-cake", "Cake"),
            ("glass-half", "Drinks"),
            ("bread-slice", "Bread"),
            ("organic-food", "Produce"),
            ("cookie", "Snacks"),
            ("fish", "Seafood"),
            ("egg", "Eggs"),
            ("chocolate", "Chocolate"),
            ("droplet", "Drinking water"),
            ("fire-flame", "Grill"),
        ]),
        group("Transport", symbol: "car", icons: [
            ("car", "Car"),
            ("taxi", "Taxi"),
            ("bus", "Bus"),
            ("train", "Train"),
            ("tram", "Tram"),
            ("bicycle", "Bicycle"),
            ("motorbike", "Motorbike"),
            ("electric-scooter", "Electric scooter"),
            ("gas", "Fuel"),
            ("ev-station", "EV charging"),
            ("parking", "Parking"),
            ("delivery-truck", "Truck"),
            ("wrench", "Mechanic"),
        ]),
        group("Travel & outdoors", symbol: "airplane", icons: [
            ("airplane", "Flight"),
            ("luggage", "Luggage"),
            ("passport", "Passport & visas"),
            ("bed", "Hotel"),
            ("ferry", "Ferry"),
            ("map", "Map"),
            ("map-pin", "Place"),
            ("globe", "World"),
            ("tent", "Camping"),
            ("trekking", "Hiking"),
            ("sea-and-sun", "Beach"),
        ]),
        group("Home & bills", symbol: "home-simple", icons: [
            ("home-simple", "Home"),
            ("building", "Building"),
            ("key", "Keys"),
            ("sofa", "Furniture"),
            ("lamp", "Lighting"),
            ("flash", "Electricity"),
            ("droplet", "Water"),
            ("fridge", "Refrigerator"),
            ("washing-machine", "Laundry"),
            ("cooking-pot", "Cookware"),
            ("cleaning", "Cleaning"),
            ("vacuum", "Vacuum cleaner"),
            ("heater", "Heating"),
            ("tools", "Repairs"),
            ("hammer", "Renovation"),
            ("color-filter", "Painting & decorating"),
            ("trash", "Waste collection"),
            ("recycling", "Recycling"),
            ("shield", "Insurance"),
            ("lock", "Security"),
        ]),
        group("Shopping", symbol: "shopping-bag", icons: [
            ("shopping-bag", "Shopping bag"),
            ("cart", "Shopping cart"),
            ("shop", "Store"),
            ("shirt", "Clothing"),
            ("sandals", "Footwear"),
            ("handbag", "Handbag"),
            ("glasses", "Glasses"),
            ("wristwatch", "Watch"),
            ("bright-star", "Jewelry"),
            ("camera", "Camera"),
            ("headset", "Audio"),
            ("computer", "Computer"),
            ("laptop", "Laptop"),
            ("smartphone-device", "Mobile phone"),
            ("tv", "Television"),
            ("package", "Delivery"),
        ]),
        group("Digital services", symbol: "cloud", icons: [
            ("software", "Apps & software"),
            ("cloud", "Cloud storage"),
            ("server", "Hosting"),
            ("sim-card", "Mobile plan"),
            ("wifi", "Internet"),
            ("phone", "Phone calls"),
        ]),
        group("Family & people", symbol: "group", icons: [
            ("user", "Person"),
            ("group", "Family & friends"),
            ("baby", "Baby"),
            ("baby-bottle", "Baby supplies"),
            ("toys", "Toys"),
        ]),
        group("Personal care", symbol: "mirror", icons: [
            ("scissor", "Haircuts"),
            ("soap", "Toiletries"),
            ("mirror", "Beauty"),
            ("hair-dryer", "Hair styling"),
            ("perfume", "Fragrance"),
        ]),
        group("Health & fitness", symbol: "healthcare", icons: [
            ("healthcare", "Medical care"),
            ("health-shield", "Health insurance"),
            ("pharmacy-cross-circle", "Pharmacy"),
            ("pharmacy-cross-tag", "Prescriptions"),
            ("home-hospital", "Hospital"),
            ("doctor", "Doctor"),
            ("tooth", "Dental care"),
            ("cube-bandage", "First aid"),
            ("eye", "Eye care"),
            ("brain", "Mental health"),
            ("activity", "Heart care"),
            ("lab-test", "Lab tests"),
            ("wheelchair", "Mobility aids"),
            ("running", "Running"),
            ("gym", "Fitness"),
            ("yoga", "Wellness"),
        ]),
        group("Leisure & hobbies", symbol: "gamepad", icons: [
            ("bookmark-book", "Events & tickets"),
            ("movie", "Movies"),
            ("music-double-note", "Music"),
            ("antenna", "Radio"),
            ("gamepad", "Video games"),
            ("dice-five", "Games"),
            ("palette", "Art"),
            ("media-image", "Photos"),
            ("book", "Reading"),
            ("puzzle", "Puzzles"),
            ("microphone", "Karaoke"),
            ("basketball", "Basketball"),
            ("trophy", "Competition"),
            ("skateboard", "Roller skates"),
        ]),
        group("Work & education", symbol: "suitcase", icons: [
            ("suitcase", "Work & business"),
            ("graduation-cap", "Education"),
            ("school", "School"),
            ("book-stack", "Books"),
            ("bag", "School bag"),
            ("edit-pencil", "Writing"),
            ("ruler", "Design"),
            ("printer", "Printing"),
            ("calculator", "Accounting"),
            ("legal-document", "Legal services"),
            ("mail", "Postage"),
        ]),
        group("Pets & garden", symbol: "plant", icons: [
            ("wolf", "Cats"),
            ("bone", "Dog supplies"),
            ("fish", "Aquarium"),
            ("insect", "Insect"),
            ("bird", "Bird"),
            ("plant", "Plants"),
            ("leaf", "Gardening"),
            ("tree", "Trees"),
            ("flower", "Flowers"),
        ]),
        group("Brands", symbol: "brand-apple", icons: [
            ("brand-apple", "Apple"),
            ("brand-google", "Google"),
            ("brand-netflix", "Netflix"),
            ("brand-spotify", "Spotify"),
            ("brand-youtube", "YouTube"),
            ("brand-apple-music", "Apple Music"),
            ("brand-apple-tv", "Apple TV"),
            ("brand-hbo", "HBO"),
            ("brand-steam", "Steam"),
            ("brand-playstation", "PlayStation"),
            ("brand-twitch", "Twitch"),
            ("brand-patreon", "Patreon"),
            ("brand-tinder", "Tinder"),
            ("brand-ebay", "eBay"),
            ("brand-airbnb", "Airbnb"),
            ("brand-uber", "Uber"),
            ("brand-paypal", "PayPal"),
            ("brand-visa", "Visa"),
            ("brand-mastercard", "Mastercard"),
            ("brand-wise", "Wise"),
            ("brand-revolut", "Revolut"),
            ("brand-alipay", "Alipay"),
            ("brand-robinhood", "Robinhood"),
        ]),
        group("Crypto", symbol: "crypto-bitcoin", icons: [
            ("crypto-bitcoin", "Bitcoin"),
            ("crypto-ethereum", "Ethereum"),
            ("crypto-solana", "Solana"),
            ("crypto-tether", "Tether"),
            ("crypto-usdc", "USDC"),
            ("crypto-bnb", "BNB Chain"),
            ("brand-binance", "Binance"),
            ("brand-bybit", "Bybit"),
        ]),
    ]

    private static let russianSuggestionTerms: [String: [String]] = [
        "label": ["метка", "тег", "прочее"],
        "star": ["звезда", "избранное"],
        "heart": ["сердце", "любовь"],
        "folder": ["папка"],
        "gift": ["подарок", "подарки"],
        "calendar": ["календарь"],
        "cash": ["наличные", "наличка"],
        "credit-card": ["банковская карта", "кредитная карта", "карта", "кредитка"],
        "bank": ["банк", "банковский счёт"],
        "wallet": ["кошелёк"],
        "coins": ["монеты"],
        "piggy-bank": ["накопления", "сбережения", "копилка"],
        "target": ["цель", "финансовая цель"],
        "safe": ["резерв", "финансовая подушка", "сейф"],
        "graph-up": ["инвестиции", "акции", "брокер"],
        "percentage": ["проценты", "комиссия", "комиссии"],
        "taxes": ["налог", "налоги"],
        "page": ["счета", "квитанции", "чеки"],
        "percentage-circle": ["бюджет"],
        "repeat": ["подписки", "автоплатёж", "регулярный платёж"],
        "coins-swap": ["перевод", "переводы"],
        "undo": ["возврат", "возвраты"],
        "charity": ["благотворительность", "пожертвования"],
        "cutlery": ["еда", "питание", "ресторан", "обед"],
        "coffee-cup": ["кофе", "кофейня"],
        "pizza-slice": ["доставка еды", "еда на вынос", "пицца"],
        "cart": ["продукты", "супермаркет", "продуктовый магазин", "корзина"],
        "birthday-cake": ["торт", "выпечка"],
        "glass-half": ["напитки", "бар", "алкоголь"],
        "bread-slice": ["хлеб", "пекарня"],
        "organic-food": ["овощи", "фрукты"],
        "cookie": ["снеки", "перекус", "сладости"],
        "fish": ["рыба", "морепродукты", "аквариум"],
        "egg": ["яйца"],
        "chocolate": ["шоколад"],
        "droplet": ["вода", "питьевая вода"],
        "fire-flame": ["гриль", "шашлык"],
        "car": ["машина", "автомобиль", "авто"],
        "taxi": ["такси"],
        "bus": ["автобус"],
        "train": ["поезд", "железная дорога"],
        "tram": ["трамвай"],
        "bicycle": ["велосипед"],
        "motorbike": ["мотоцикл"],
        "electric-scooter": ["самокат", "электросамокат"],
        "gas": ["бензин", "топливо", "заправка"],
        "ev-station": ["зарядка электромобиля", "электрозаправка"],
        "parking": ["парковка"],
        "delivery-truck": ["грузовик", "грузоперевозки"],
        "wrench": ["автосервис", "механик", "ремонт машины"],
        "airplane": ["самолёт", "авиабилеты", "перелёт"],
        "luggage": ["багаж", "чемодан"],
        "passport": ["паспорт", "виза", "визы"],
        "bed": ["отель", "гостиница", "жильё"],
        "ferry": ["паром"],
        "map": ["карта местности", "маршрут"],
        "map-pin": ["место", "локация"],
        "globe": ["мир", "путешествия"],
        "tent": ["кемпинг", "палатка"],
        "trekking": ["поход", "туризм"],
        "sea-and-sun": ["пляж", "море", "отпуск"],
        "home-simple": ["дом", "жильё"],
        "building": ["здание", "квартира"],
        "key": ["ключ", "ключи"],
        "sofa": ["мебель", "диван"],
        "lamp": ["освещение", "лампа"],
        "flash": ["электричество", "свет"],
        "fridge": ["холодильник"],
        "washing-machine": ["стирка", "прачечная", "стиральная машина"],
        "cooking-pot": ["посуда", "кухонная утварь"],
        "cleaning": ["уборка", "клининг"],
        "vacuum": ["пылесос"],
        "heater": ["отопление", "обогрев"],
        "tools": ["ремонт", "инструменты"],
        "hammer": ["ремонт квартиры", "реновация"],
        "color-filter": ["покраска", "декор"],
        "trash": ["мусор", "вывоз мусора"],
        "recycling": ["переработка", "сортировка мусора"],
        "shield": ["страховка", "страхование"],
        "lock": ["безопасность", "охрана"],
        "shopping-bag": ["покупки", "шопинг"],
        "shop": ["магазин"],
        "shirt": ["одежда"],
        "sandals": ["обувь"],
        "handbag": ["сумка", "сумки"],
        "glasses": ["очки"],
        "wristwatch": ["часы"],
        "bright-star": ["украшения", "ювелирные изделия"],
        "camera": ["камера", "фотоаппарат"],
        "headset": ["аудио", "наушники"],
        "computer": ["компьютер"],
        "laptop": ["ноутбук"],
        "smartphone-device": ["телефон", "смартфон"],
        "tv": ["телевизор"],
        "package": ["доставка", "посылка"],
        "software": ["приложения", "софт", "программы"],
        "cloud": ["облако", "облачное хранилище"],
        "server": ["хостинг", "сервер"],
        "sim-card": ["мобильная связь", "тариф", "сим-карта"],
        "wifi": ["интернет", "вайфай"],
        "phone": ["звонки", "телефонная связь"],
        "brand-airbnb": ["эйрбиэнби", "аренда", "жильё"],
        "brand-alipay": ["алипэй", "платежи"],
        "brand-apple": ["эпл", "айфон"],
        "brand-apple-music": ["эпл мьюзик", "музыка"],
        "brand-apple-tv": ["эпл тв", "кино", "сериалы"],
        "brand-binance": ["бинанс", "криптобиржа", "биржа"],
        "brand-bybit": ["байбит", "криптобиржа", "биржа"],
        "brand-ebay": ["ибэй", "магазин"],
        "brand-google": ["гугл"],
        "brand-hbo": ["эйчбиоу", "кино", "сериалы"],
        "brand-mastercard": ["мастеркард", "карта"],
        "brand-netflix": ["нетфликс", "кино", "сериалы"],
        "brand-patreon": ["патреон", "подписка"],
        "brand-paypal": ["пэйпал", "платежи"],
        "brand-playstation": ["плейстейшн", "игры"],
        "brand-revolut": ["револют", "банк"],
        "brand-robinhood": ["робингуд", "инвестиции"],
        "brand-spotify": ["спотифай", "музыка"],
        "brand-steam": ["стим", "игры"],
        "brand-tinder": ["тиндер", "знакомства"],
        "brand-twitch": ["твич", "стримы"],
        "brand-uber": ["убер", "такси"],
        "brand-visa": ["виза", "карта"],
        "brand-wise": ["вайз", "переводы"],
        "brand-youtube": ["ютуб", "видео"],
        "crypto-bitcoin": ["биткоин", "криптовалюта"],
        "crypto-ethereum": ["эфириум", "эфир", "криптовалюта"],
        "crypto-solana": ["солана", "криптовалюта"],
        "crypto-tether": ["тезер", "usdt", "стейблкоин"],
        "crypto-usdc": ["юэсдиси", "стейблкоин"],
        "crypto-bnb": ["бинанс", "bnb", "криптовалюта"],
        "crypto-xrp": ["рипл", "xrp", "криптовалюта"],
        "crypto-cardano": ["кардано", "ada", "криптовалюта"],
        "user": ["человек", "персона"],
        "group": ["семья", "друзья"],
        "baby": ["ребёнок", "дети"],
        "baby-bottle": ["товары для детей", "детское питание"],
        "toys": ["игрушки"],
        "scissor": ["стрижка", "парикмахерская"],
        "soap": ["гигиена", "туалетные принадлежности"],
        "mirror": ["красота", "косметика"],
        "hair-dryer": ["укладка", "фен"],
        "perfume": ["парфюм", "духи"],
        "healthcare": ["медицина", "здоровье", "лечение"],
        "health-shield": ["медицинская страховка", "медицинское страхование"],
        "pharmacy-cross-circle": ["аптека", "лекарства"],
        "pharmacy-cross-tag": ["рецепты", "лекарства по рецепту"],
        "home-hospital": ["больница", "клиника"],
        "doctor": ["врач", "доктор"],
        "tooth": ["стоматолог", "зубы"],
        "cube-bandage": ["первая помощь", "аптечка"],
        "eye": ["зрение", "офтальмолог"],
        "brain": ["психолог", "психотерапия", "ментальное здоровье"],
        "activity": ["сердце", "кардиолог"],
        "lab-test": ["анализы", "лаборатория"],
        "wheelchair": ["инвалидная коляска", "средства реабилитации"],
        "running": ["бег"],
        "gym": ["спортзал", "фитнес"],
        "yoga": ["йога", "велнес"],
        "bookmark-book": ["билеты", "мероприятия"],
        "movie": ["кино", "фильмы"],
        "music-double-note": ["музыка"],
        "antenna": ["радио"],
        "gamepad": ["видеоигры", "игры"],
        "dice-five": ["настольные игры"],
        "palette": ["искусство", "рисование"],
        "media-image": ["фото", "фотографии"],
        "book": ["чтение", "книги"],
        "puzzle": ["пазлы", "головоломки"],
        "microphone": ["караоке"],
        "basketball": ["баскетбол"],
        "trophy": ["соревнования", "награда"],
        "skateboard": ["ролики", "роликовые коньки"],
        "suitcase": ["работа", "бизнес"],
        "graduation-cap": ["образование", "учёба"],
        "school": ["школа"],
        "book-stack": ["учебники", "книги"],
        "bag": ["рюкзак", "школьная сумка"],
        "edit-pencil": ["письмо", "канцелярия"],
        "ruler": ["дизайн", "проектирование"],
        "printer": ["печать", "принтер"],
        "calculator": ["бухгалтерия", "учёт"],
        "legal-document": ["юрист", "юридические услуги"],
        "mail": ["почта", "пересылка"],
        "wolf": ["кошки", "кот", "котик"],
        "bone": ["собака", "товары для собак"],
        "insect": ["насекомые"],
        "bird": ["птица", "птицы"],
        "plant": ["растения"],
        "leaf": ["сад", "садоводство"],
        "tree": ["деревья"],
        "flower": ["цветы"],
    ]

    static let choices = groups.flatMap(\.icons).map(\.symbol).reduce(into: [String]()) { choices, symbol in
        guard !choices.contains(symbol) else { return }
        choices.append(symbol)
    }

    static func suggestions(matching query: String, limit: Int = 10) -> [IconPickerOption] {
        groups.flatMap(\.icons).filter {
            $0.matchesSuggestion(query)
        }.reduce(into: [IconPickerOption]()) { result, option in
            guard result.count < limit,
                  !result.contains(where: { $0.symbol == option.symbol }) else { return }
            result.append(option)
        }
    }

    static func group(containing symbol: String) -> IconPickerGroup? {
        groups.first { group in
            group.icons.contains { $0.symbol == AppIcons.canonicalName(symbol) }
        }
    }

    private static func group(
        _ title: String,
        symbol: String,
        icons: [(String, String)]
    ) -> IconPickerGroup {
        IconPickerGroup(
            title: title,
            symbol: symbol,
            icons: icons.map { icon in
                IconPickerOption(
                    symbol: icon.0,
                    title: icon.1,
                    suggestionTerms: russianSuggestionTerms[icon.0, default: []]
                )
            }
        )
    }
}
